before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

stages:
  - scan
  - build docker
  - deploy

ui:
  stage: build docker
  script:
    - cd weather-ui
    - docker build -t $DOCKER_REGISTRY/weather/weather-ui:v3.0.6 .
    - docker push $DOCKER_REGISTRY/weather/weather-ui:v3.0.6


server:
  stage: build docker
  script:
    - cd weather-server
    - docker build -t $DOCKER_REGISTRY/weather/weather-server:v4.0.6 . --no-cache
    - docker push $DOCKER_REGISTRY/weather/weather-server:v4.0.6

transfer:
  stage: build docker
  script:
    - cd weather-transfer
    - docker build -t $DOCKER_REGISTRY/weather/weather-transfer:2.1.5 . --no-cache
    - docker push $DOCKER_REGISTRY/weather/weather-transfer:2.1.5


deploy:
  stage: deploy
  script:
    - sed -i "s/WEATHER_API=/WEATHER_API=$WEATHERAPI/g" docker-compose.yml
    - sed -i "s/DB_PASSWORD=/DB_PASSWORD=$DB_PASSWORD/g" docker-compose.yml
    - scp docker-compose.yml $DEPLOY_HOST:/opt/weather
    - ssh $DEPLOY_HOST "cd /opt/weather/ && docker-compose pull && docker-compose down && docker-compose up -d
    - git reset --hard
  rules:
    - changes:
        - docker-compose.yml
      when: on_success