before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

variables:
  UI_VERSION: "v3.2.0"
  SERVER_VERSION: "v5.0.0"
  PROCESSOR_VERSION: "v3.0.0"
#  RECEIVER_VERSION: "v1.0.0"
  STATS_VERSION: "v1.0.0"

stages:
  - scan
  - build docker
#  - deploy

ui:
  stage: build docker
  script:
    - cd ui
    - docker build -t $CI_REGISTRY/weather/ui:$UI_VERSION . --no-cache
    - docker push $CI_REGISTRY/weather/ui:$UI_VERSION

stats:
  stage: build docker
  script:
    - cd stats
    - docker build -t $CI_REGISTRY/weather/stats:$STATS_VERSION . --no-cache
    - docker push $CI_REGISTRY/weather/stats:$STATS_VERSION

server:
  stage: build docker
  script:
    - cd server
    - docker build -t $CI_REGISTRY/weather/server:$SERVER_VERSION . --no-cache
    - docker push $CI_REGISTRY/weather/server:$SERVER_VERSION

processor:
  stage: build docker
  script:
    - cd processor
    - docker build -t $CI_REGISTRY/weather/processor:$PROCESSOR_VERSION . --no-cache
    - docker push $CI_REGISTRY/weather/processor:$PROCESSOR_VERSION

#receiver:
#  stage: build docker
#  script:
#    - cd receiver
#    - docker build -t $CI_REGISTRY/weather/receiver:$RECEIVER_VERSION . --no-cache
#    - docker push $CI_REGISTRY/weather/receiver:$RECEIVER_VERSION

#deploy:
#  stage: deploy
#  script:
#    - sed -i "s/WEATHER_API=/WEATHER_API=$WEATHERAPI/g" docker-compose.yml
#    - sed -i "s/DB_PASSWORD=/DB_PASSWORD=$DB_PASSWORD/g" docker-compose.yml
#    - scp docker-compose.yml $DEPLOY_HOST:/opt/weather
#    - ssh $DEPLOY_HOST "cd /opt/weather/ && docker-compose pull && docker-compose down && docker-compose up -d"
#    - git reset --hard
#  rules:
#    - changes:
#        - docker-compose.yml
#      when: on_success