
name: weather
# Define the services (containers)
services:
  server:
    container_name: weather-server
    image: docker.zoms.net/weather/server:v5.0.1
    restart: unless-stopped
    pull_policy: always
    # Expose port 3000 inside the container to port 6001 on the host
    ports:
      - "6001:3000"
    # Set the environment variables
    environment:
      - PORT=3000
      - DB_HOST=10.10.1.120
      - DB_USER=ambient
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=ambient
      - ENV=Production
      - LOGLEVEL=Info
      - LAT=38.725798
      - LON=-104.66783
    # Attach the container to the custom network
    networks:
      - weather-network
    extra_hosts:
      - "zoms-gitlab:10.10.1.124"
  processor:
    container_name: weather-processor
    image: docker.zoms.net/weather/processor:v3.0.1
    restart: unless-stopped
    pull_policy: always
    # Expose port 3000 inside the container to port 6001 on the host
    ports:
      - "7501:8081"
    # Set the environment variables
    environment:
      - MQTT_BROKER=tcp://10.10.1.124:1883
      - MQTT_CLIENT_ID=weather-processor
      - MQTT_USER=brian
      - MQTT_PASS=${DB_PASSWORD}
      - MQTT_TOPIC=ambient/#
      - MQTT_STATS_TOPIC=weather/stats
      - DATABASE_URL=postgres://ambient:${DB_PASSWORD}@10.10.1.120:5432/ambient?sslmode=disable
      - STATION_MAC=WS-5000
      - ELEVATION=1746.5
      - SNAPSHOT_INTERVAL=1m
      - RAIN_EVENT_GAP=1h
    # Attach the container to the custom network
    networks:
      - weather-network
    extra_hosts:
      - "zoms-gitlab:10.10.1.124"
  stats:
    container_name: weather-stats
    image: docker.zoms.net/weather/stats:v1.0.0
    restart: unless-stopped
    pull_policy: always
    # Expose port 3000 inside the container to port 6001 on the host
    ports:
      - "7500:8080"
    # Set the environment variables
    environment:
      - MQTT_BROKER=tcp://10.10.1.124:1883
      - MQTT_CLIENT_ID=weather-stats
      - MQTT_USERNAME=brian
      - MQTT_PASSWORD=${DB_PASSWORD}
      - MQTT_STATS_SUBSCRIBE=weather/stats
      - STATION_MAC=WS-5000
      - DATABASE_URL=postgres://ambient:${DB_PASSWORD}@10.10.1.120:5432/ambient?sslmode=disable
      - ALERT_CRON=*/15 * * * *
      - FORECAST_CRON=0 */4 * * *
      - LAT=38.725798
      - LON=-104.66783
      - WEATHER_API=${WEATHER_API}

    # Attach the container to the custom network
    networks:
      - weather-network
    extra_hosts:
      - "zoms-gitlab:10.10.1.124"

  weather-ui:
    container_name: weather-ui
    image: docker.zoms.net/weather/ui:v3.2.0
    restart: unless-stopped
    pull_policy: always
    # Expose port 6000 inside the container to port 6000 on the host
    ports:
      - "6000:6000"
    # Attach the container to the custom network
    networks:
      - weather-network

# Define the custom network
networks:
  weather-network:
    driver: bridge
