apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-server-deployment
  labels:
    app: weather-server-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: weather-server-deployment
  template:
    metadata:
      labels:
        app: weather-server-deployment
    spec:
      containers:
        - image: docker.zoms.net/weather-server:latest
          name: weather-server-deployment
          imagePullPolicy: Always
          ports:
            - name: weather-server
              containerPort: 3000
              protocol: TCP
          env:
            - name: AMBIENT_WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: apikey
            - name: AMBIENT_WEATHER_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: appkey
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: database
            - name: DARKSKY
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: darksky
            - name: IPGEO
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: ipgeo
            - name: LAT
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: lat
            - name: LON
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: lon
            - name: METAR
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: metar
      imagePullSecrets:
        - name: zoms
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: weather-server-service
  name: weather-server-service
spec:
  ports:
    - port: 3000
  selector:
    app: weather-server-deployment