apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-ui-deployment
  labels:
    app: weather-ui-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: weather-ui-deployment
  template:
    metadata:
      labels:
        app: weather-ui-deployment
    spec:
      containers:
        - image: docker.zoms.net/weather-ui:1.0
          name: weather-ui-deployment
          imagePullPolicy: Always
          ports:
            - name: weather-ui
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: zoms
      restartPolicy: Always