pipeline {
    agent any
    environment {
        registry = "docker.zoms.net"
        registryCredential = "zoms-docker"
        serverImage = ''
        dataImage = ''
        uiImage = ''
    }
    stages {

        stage('checkout') {
            steps {
                cleanWs()
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [[credentialsId: 'spectre013',
                    url: 'git@github.com:spectre013/ambient-weather.git']]])
            }
        }
        stage('Building Data') {
              steps{
                script {
                      dataImage = docker.build("${registry}/weather-data:latest","./weather-data/")
                }
              }
            }
            stage('Deploy Data') {
              steps{
                script {
                  docker.withRegistry("https://${registry}", registryCredential) {
                    dataImage.push()
                }
                }
              }
            }
            stage('Remove Data') {
              steps{
                sh "docker rmi ${registry}/weather-data:latest"
              }
            }
    }
}