export interface Current {
    id: number
    mac: string
    date: string
    baromabsin: number
    baromrelin: number
    battout: number
    batt1: number
    batt2: number
    batt3: number
    batt4: number
    batt5: number
    batt6: number
    batt7: number
    batt8: number
    batt9: number
    batt10: number
    battlightning: number
    co2: number
    dailyrainin: number
    dewpoint: number
    eventrain: number
    feelslike: number
    hourlyrainin: number
    hourlyrain: number
    humidity: number
    humidity1: number
    humidity2: number
    humidity3: number
    humidity4: number
    humidity5: number
    humidity6: number
    humidity7: number
    humidity8: number
    humidity9: number
    humidity10: number
    humidityin: number
    lastrain: string
    maxdailygust: number
    relay1: number
    relay2: number
    relay3: number
    relay4: number
    relay5: number
    relay6: number
    relay7: number
    relay8: number
    relay9: number
    relay10: number
    monthlyrainin: number
    solarradiation: number
    tempf: number
    temp1f: number
    temp2f: number
    temp3f: number
    temp4f: number
    temp5f: number
    temp6f: number
    temp7f: number
    temp8f: number
    temp9f: number
    temp10f: number
    tempinf: number
    totalrainin: number
    uv: number
    weeklyrainin: number
    winddir: number
    windgustmph: number
    windgustdir: number
    windspeedmph: number
    yearlyrainin: number
    lightningday: number
    lightninghour: number
    lightningdistance: number
    lightningtime: string
    aqipm25: number
    aqipm2524h: number
}
