from datetime import datetime
from db import db

class WeatherData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    mac = db.Column(db.String(17), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    baromabsin = db.Column(db.Float)
    baromrelin = db.Column(db.Float)
    battout = db.Column(db.Integer)
    batt1 = db.Column(db.Integer)
    batt2 = db.Column(db.Integer)
    batt3 = db.Column(db.Integer)
    batt4 = db.Column(db.Integer)
    batt5 = db.Column(db.Integer)
    batt6 = db.Column(db.Integer)
    batt7 = db.Column(db.Integer)
    batt8 = db.Column(db.Integer)
    batt9 = db.Column(db.Integer)
    batt10 = db.Column(db.Integer)
    battlightning = db.Column(db.Integer)
    co2 = db.Column(db.Integer)
    dailyrainin = db.Column(db.Float)
    dewpoint = db.Column(db.Float)
    eventrain = db.Column(db.Float)
    feelslike = db.Column(db.Float)
    hourlyrainin = db.Column(db.Float)
    hourlyrain = db.Column(db.Float)
    humidity = db.Column(db.Integer)
    humidity1 = db.Column(db.Integer)
    humidity2 = db.Column(db.Integer)
    humidity3 = db.Column(db.Integer)
    humidity4 = db.Column(db.Integer)
    humidity5 = db.Column(db.Integer)
    humidity6 = db.Column(db.Integer)
    humidity7 = db.Column(db.Integer)
    humidity8 = db.Column(db.Integer)
    humidity9 = db.Column(db.Integer)
    humidity10 = db.Column(db.Integer)
    humidityin = db.Column(db.Integer)
    lastrain = db.Column(db.DateTime)
    maxdailygust = db.Column(db.Float)
    relay1 = db.Column(db.Integer)
    relay2 = db.Column(db.Integer)
    relay3 = db.Column(db.Integer)
    relay4 = db.Column(db.Integer)
    relay5 = db.Column(db.Integer)
    relay6 = db.Column(db.Integer)
    relay7 = db.Column(db.Integer)
    relay8 = db.Column(db.Integer)
    relay9 = db.Column(db.Integer)
    relay10 = db.Column(db.Integer)
    monthlyrainin = db.Column(db.Float)
    solarradiation = db.Column(db.Float)
    tempf = db.Column(db.Float)
    temp1f = db.Column(db.Float)
    temp2f = db.Column(db.Float)
    temp3f = db.Column(db.Float)
    temp4f = db.Column(db.Float)
    temp5f = db.Column(db.Float)
    temp6f = db.Column(db.Float)
    temp7f = db.Column(db.Float)
    temp8f = db.Column(db.Float)
    temp9f = db.Column(db.Float)
    temp10f = db.Column(db.Float)
    tempinf = db.Column(db.Float)
    totalrainin = db.Column(db.Float)
    uv = db.Column(db.Integer)
    weeklyrainin = db.Column(db.Float)
    winddir = db.Column(db.Integer)
    windgustmph = db.Column(db.Float)
    windgustdir = db.Column(db.Integer)
    windspeedmph = db.Column(db.Float)
    yearlyrainin = db.Column(db.Float)
    lightningday = db.Column(db.Integer)
    lightninghour = db.Column(db.Integer)
    lightningdistance = db.Column(db.Integer)
    lightningtime = db.Column(db.DateTime)
    aqipm25 = db.Column(db.Integer)
    aqipm2524h = db.Column(db.Integer)

    def __repr__(self):
        return f"<WeatherData {self.id} - {self.date}>"
