UPDATE records SET battout = '' where battout IS NULL;
UPDATE records SET batt1 = '' where batt1 IS NULL;
UPDATE records SET batt2 = '' where batt2 IS NULL;
UPDATE records SET batt3 = '' where batt3 IS NULL;
UPDATE records SET batt4 = '' where batt4 IS NULL;
UPDATE records SET batt5 = '' where batt5 IS NULL;
UPDATE records SET batt6 = '' where batt6 IS NULL;
UPDATE records SET batt7 = '' where batt7 IS NULL;
UPDATE records SET batt8 = '' where batt8 IS NULL;
UPDATE records SET batt9 = '' where batt9 IS NULL;
UPDATE records SET batt10 = '' where batt10 IS NULL;
UPDATE records SET `mac` = '' where max IS NULL;
UPDATE records SET `baromabsin` = 0.0 where `baromabsin` IS NULL;
UPDATE records SET `baromrelin` = 0.0 where `baromrelin` IS NULL;
UPDATE records SET `co2` = 0.0 where `co2` IS NULL;
UPDATE records SET `dailyrainin` = 0.0 where `dailyrainin` IS NULL;
UPDATE records SET `dewpoint` = 0.0 where `dewpoint` IS NULL;
UPDATE records SET `eventrainin` = 0.0 where `eventrainin` IS NULL;
UPDATE records SET `feelslike` = 0.0 where `feelslike` IS NULL;
UPDATE records SET `hourlyrainin` = 0.0 where `hourlyrainin` IS NULL;
UPDATE records SET `maxdailygust` = 0.0 where `maxdailygust` IS NULL;
UPDATE records SET `monthlyrainin` = 0.0 where `monthlyrainin` IS NULL;
UPDATE records SET `solarradiation` = 0.0 where `solarradiation` IS NULL;
UPDATE records SET `tempf` = 0.0 where `tempf` IS NULL;
UPDATE records SET `temp1f` = 0.0 where `temp1f` IS NULL;
UPDATE records SET `temp2f` = 0.0 where `temp2f` IS NULL;
UPDATE records SET `temp3f` = 0.0 where `temp3f` IS NULL;
UPDATE records SET `temp4f` = 0.0 where `temp4f` IS NULL;
UPDATE records SET `temp5f` = 0.0 where `temp5f` IS NULL;
UPDATE records SET `temp6f` = 0.0 where `temp6f` IS NULL;
UPDATE records SET `temp7f` = 0.0 where `temp7f` IS NULL;
UPDATE records SET `temp8f` = 0.0 where `temp8f` IS NULL;
UPDATE records SET `temp9f` = 0.0 where `temp9f` IS NULL;
UPDATE records SET `temp10f` = 0.0 where `temp10f` IS NULL;
UPDATE records SET `tempinf` = 0.0 where `tempinf` IS NULL;
UPDATE records SET `totalrainin` = 0.0 where `totalrainin` IS NULL;
UPDATE records SET `uv` = 0.0 where `uv` IS NULL;
UPDATE records SET `weeklyrainin` = 0.0 where `weeklyrainin` IS NULL;
UPDATE records SET `windgustmph` = 0.0 where `windgustmph` IS NULL;
UPDATE records SET `windspeedmph` = 0.0 where `windspeedmph` IS NULL;
UPDATE records SET `winddir_avg2m` = 0.0 where `winddir_avg2m` IS NULL;
UPDATE records SET `windspdmph_avg2m` = 0.0 where `windspdmph_avg2m` IS NULL;
UPDATE records SET `winddir_avg10m` = 0.0 where `winddir_avg10m` IS NULL;
UPDATE records SET `windspdmph_avg10m` = 0.0 where `windspdmph_avg10m` IS NULL;
UPDATE records SET `yearlyrainin` = 0.0 where `yearlyrainin` IS NULL;
UPDATE records SET `humidity` = 0 where `humidity` IS NULL;
UPDATE records SET `humidity1` = 0 where `humidity1` IS NULL;
UPDATE records SET `humidity2` = 0 where `humidity2` IS NULL;
UPDATE records SET `humidity3` = 0 where `humidity3` IS NULL;
UPDATE records SET `humidity4` = 0 where `humidity4` IS NULL;
UPDATE records SET `humidity5` = 0 where `humidity5` IS NULL;
UPDATE records SET `humidity6` = 0 where `humidity6` IS NULL;
UPDATE records SET `humidity7` = 0 where `humidity7` IS NULL;
UPDATE records SET `humidity8` = 0 where `humidity8` IS NULL;
UPDATE records SET `humidity9` = 0 where `humidity9` IS NULL;
UPDATE records SET `humidity10` = 0 where `humidity10` IS NULL;
UPDATE records SET `humidityin` = 0 where `humidityin` IS NULL;
UPDATE records SET `relay1` = 0 where `relay1` IS NULL;
UPDATE records SET `relay2` = 0 where `relay2` IS NULL;
UPDATE records SET `relay3` = 0 where `relay3` IS NULL;
UPDATE records SET `relay4` = 0 where `relay4` IS NULL;
UPDATE records SET `relay5` = 0 where `relay5` IS NULL;
UPDATE records SET `relay6` = 0 where `relay6` IS NULL;
UPDATE records SET `relay7` = 0 where `relay7` IS NULL;
UPDATE records SET `relay8` = 0 where `relay8` IS NULL;
UPDATE records SET `relay9` = 0 where `relay9` IS NULL;
UPDATE records SET `relay10` = 0 where `relay10` IS NULL;
UPDATE records SET `winddir` = 0 where `winddir` IS NULL;
UPDATE records SET `windgustdir` = 0 where `windgustdir` IS NULL;

ALTER TABLE records MODIFY COLUMN `mac` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `date` NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE records MODIFY COLUMN `baromabsin` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `baromrelin` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `battout` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt1` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt2` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt3` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt4` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt5` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt6` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt7` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt8` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt9` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `batt10` varchar(255) NOT NULL DEFAULT ' ';
ALTER TABLE records MODIFY COLUMN `co2` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `dailyrainin` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `dewpoint` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `eventrainin` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `feelslike` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `hourlyrainin` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `humidity` double NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity1` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity2` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity3` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity4` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity5` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity6` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity7` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity8` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity9` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidity10` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `humidityin` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `lastrain` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE records MODIFY COLUMN `maxdailygust` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `relay1` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay2` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay3` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay4` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay5` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay6` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay7` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay8` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay9` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `relay10` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `monthlyrainin` NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `solarradiation` NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `tempf` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp1f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp2f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp3f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp4f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp5f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp6f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp7f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp8f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp9f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `temp10f` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `tempinf` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `totalrainin` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `uv` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `weeklyrainin` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `winddir` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `windgustmph` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `windgustdir` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `windspeedmph` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `winddir_avg2m` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `windspdmph_avg2m` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `winddir_avg10m` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `windspdmph_avg10m` double NOT NULL DEFAULT 0.0;
ALTER TABLE records MODIFY COLUMN `yearlyrainin` double NOT NULL DEFAULT 0.0;

ALTER TABLE records MODIFY COLUMN `lightning_hour` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `lightning_time` int(11) NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `lightning_distance` DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE records MODIFY COLUMN `lightning_day` int(11) NOT NULL DEFAULT 0;